name: Add new bugs & PRs to This Week project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

permissions: {}
jobs:
  add-to-project:
    name: Add new bugs and PRs to This Week project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/immanuelkumar87/Laravel-CRUD.git
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
